#!/usr/bin/env ruby
File.unlink '/publify/tmp/pids/server.pid' if File.exist? '/publify/tmp/pids/server.pid'
begin
  load File.expand_path("../spring", __FILE__)
rescue LoadError
end
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require_relative '../config/boot'
require 'rails/commands'
