#
# Copyright (C) 2017 XLAB d.o.o.
#
# This work is open source software, licensed under the terms of the
# BSD license as described in the LICENSE file in the top-level directory.
#

.PHONY: module
module:
	./GET

clean:
	rm -rf build
